/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:75c613ee-0c28-4deb-9baf-d15761390444",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_1317juxRK",
    "aws_user_pools_web_client_id": "5fomh2t1te65rbthbi5qa627gr",
    "oauth": {}
};


export default awsmobile;
